version: 0.2
            
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - echo build
  post_build:
    commands:
    - mvn package
      - echo post_build
      -mv target/demo ./
artifacts:
  files:
     - demo/**/*
  discard-paths: yes
